### ISSUE TITLE
Bug: SigmaCollection.load_ruleset not throwing error for empty file

### ISSUE THREAD

**Issue by KevDenis** [SigmaHQ/pySigma#103]
### Steps to reproduce

Create an empty file `rule.yml` in `/tmp` for example.

And run:
```
collection = SigmaCollection.load_ruleset(["/tmp/rule.yml"])
print(collection)
```

which produce this output:
```
SigmaCollection(rules=[], errors=[])
```

But there are no errors that are thrown.
Is this normal?

**Comment by thomaspatzke** [comment]
Yes, even when it appears to make no sense to create empty rule collection objects from YAML input, technically there's nothing bad about it. And there might be legitimate use cases for it, e.g. ignoring empty placeholder files in input directories and likely others.
