### ISSUE TITLE
S1 Max Operators

### ISSUE THREAD

**Issue by clairmont32** [SigmaHQ/pySigma#116]
Hello,

The SentinelOne backend doesnt seem to handle lengthy lists within a field's key such as CommandLine|contains|any. For example, proc_creation_macos_disable_security_tools.yml ends up exceeding S1's max operators limit of 20, thus needing manual modification.

A handful of the Mac specific rules have this issue after iterating through the majority of them.

**Comment by thomaspatzke** [comment]
Sorry, wrong repository. pSigma is the base for the backends, please [open the issue in the S1 backend project](https://github.com/7RedViolin/pySigma-backend-sentinelone/issues/new).
