### ISSUE TITLE
Fork workflows fail

### ISSUE THREAD

**Issue by frack113** [SigmaHQ/pySigma#12]
Hi,
the `Create coverage badge` allways fail in my fork
Can you explaint how create `auth`.
`gistID` is written in hard so I think it is a dead end.

**Comment by thomaspatzke** [comment]
The auth token is generated for the Gist containing the badge data. I think it's better to disable badge generation for forks by checking for the main repository. Will try this now...

**Comment by thomaspatzke** [comment]
Done in this commit: d2ed9dc1fadc919e206a4493f4721624ae8ffd74

Please try if the test now runs in your fork, @frack113.

**Comment by frack113** [comment]
Thanks All is green 👍
