### ISSUE TITLE
Connect Multiple New Conditions by Pipeline with OR

### ISSUE THREAD

**Issue by Mat0vu** [SigmaHQ/pySigma#136]
Hello,

I´m currently working on replacing the old sigmac converter with Pysigma while trying to get the same output as with the old code which contains some custom changes that were implemented in our company.
When experimenting with pipelines I came across the following issue: 

For some rules (e.g. rules that detect process creations or registry events) we have added more conditions to the query so that our backend (elasticsearch) filters for both windows and sysmon events.

Part of the Pipeline declaration looks like this:
```
process_creation_windows:
  category: process_creation
  product: windows
  conditions:
    EventID: 4688
    Channel: Security

process_creation_sysmon:
  category: process_creation
  product: windows
  conditions:
    EventID: 1
    Channel: 'Microsoft-Windows-Sysmon/Operational'
```

The Pipeline code looks like this
```
[
  ProcessingItem(
    identifier=f"Add_{field_name}_condition",
        transformation=AddConditionTransformation(
            get_value_by_key_or_None(d=mappings, key="conditions"),
        ),
        rule_conditions=[
            LogsourceCondition(
                category=get_value_by_key_or_None(d=mappings, key="category"),
                product=get_value_by_key_or_None(d=mappings, key="product"),
                service=get_value_by_key_or_None(d=mappings, key="service"),
            )
        ]
        )
        for field_name, mappings in read_customer_specific_index_setting(customer=customer).items()
])
```

After converting a sigma rule with 
```
category: process_creation
product: windows
```

The rule has following processing items applied. 
```
'Add_process_creation_windows_condition'
'Add_process_creation_sysmon_condition'
```

And the query looks something like this
`(evt.system.EventID:1 AND evt.system.Channel:Microsoft\\-Windows\\-Sysmon\\/Operational) AND ((evt.system.EventID:4688 AND evt.system.Channel:Security) AND …………….`

This behaviour is as expected because two new AND conditions are added by the function AddConditionTransformation. However, logs will not have EventID 1 AND 4688, so this search will not bring any result.

The query should look like this:
`(evt.system.EventID:1 AND evt.system.Channel:Microsoft\\-Windows\\-Sysmon\\/Operational) OR ((evt.system.EventID:4688 AND evt.system.Channel:Security) AND …………….`

I tried to find a way to add these extra conditions connected with OR but could not find a solution.
Is it possible to configure the AddConditionTransformation function that if multiple conditions (which can possibly be nested) are added, then the connection is made with OR?
This should only be done when these Processing Items have a similar identifier (like for example process_creation_windows and process_creation_sysmon) because otherwise it would not be possible to add other conditions that should be connected with AND.

I hope the description of this issue is clear. Thank you very much for any help and for the project in general!

Best regards

**Comment by thomaspatzke** [comment]
Hi! The `AddConditionTransformation` is restricted to add AND-linked conditions and extending it or allowing nesting etc. would be quite complex. I'm currently extending processing pipelines by query post processing that could solve your problem. Basically, it allows to add query parts statically around the query generated by the backend. I will post it here when it gets available.

**Comment by Mat0vu** [comment]
Hi Thomas! That sounds like a good solution for this issue, thank you very much for keeping me updated 👍

**Comment by thomaspatzke** [comment]
It's out 😊 [Here some first info](https://infosec.exchange/@thomaspatzke/110986371256510782) and [an example](https://gist.github.com/thomaspatzke/ea9e54a459b74e3ec9593c0329575eb8), a blog post will be published soon!
