### ISSUE TITLE
release v0.10.0 : issue with `finalize_query_{format}` being discarded ?

### ISSUE THREAD

**Issue by buixor** [SigmaHQ/pySigma#141]
Hello,

I'm working on a pySigma backend/pipeline for [crowdsec](https://github.com/crowdsecurity/crowdsec).

After upgrading pySigma to v0.10.0, I noticed that the output of `finalize_query_{format}` seems to be discarded (this was not the case before, but I was running a rather old version, I suppose).

When looking at [`finalize_query` in base.py](https://github.com/SigmaHQ/pySigma/blob/18c68e45fd1f38071bc877c43a6d1dd2c059f379/sigma/conversion/base.py#L485) it seems that the ouput of the underlying `finalize_query_{format}` call is discarded. If I'm not mistaken, `backend_query` should be passed to `self.last_processing_pipeline.postprocess_query` instead of query.

I'm not very familiar with the project so I might be wrong, but otherwise, let me know and I will be happy to open a PR!

**Comment by cyberphor** [comment]
@buixor I submitted a [pull request](https://github.com/SigmaHQ/pySigma/pull/140) for the same issue the other day.

**Comment by thomaspatzke** [comment]
I released version 0.10.1 with the fix of @cyberphor.
