### ISSUE TITLE
pipenv install fails on Debian / Ubuntu

### ISSUE THREAD

**Issue by rpet** [SigmaHQ/pySigma#15]
Running `pipenv install ` on a Debian 11 fresh installation aborts installation with this messages (the same happens on Debian 10):

```
$ pipenv install git+https://github.com/SigmaHQ/pySigma.git#main
Creating a virtualenv for this project…
Using /usr/bin/python3 (3.9.2) to create virtualenv…
⠋created virtual environment CPython3.9.2.final.0-64 in 108ms
  creator CPython3Posix(dest=/home/rpet/.local/share/virtualenvs/rpet-HtsefH42, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/rpet/.local/share/virtualenv)
    added seed packages: pip==20.3.4, pkg_resources==0.0.0, setuptools==44.1.1, wheel==0.34.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Virtualenv location: /home/rpet/.local/share/virtualenvs/rpet-HtsefH42
Creating a Pipfile for this project…
Installing git+https://github.com/SigmaHQ/pySigma.git#main…
WARNING: Invalid fragment string main
ABORTING INSTALL... You will have to reinstall any packages that failed to install.
⠙You may have to manually run pipenv lock when you are finished.
```
Could you please tell me in wich operating systems has been tested the installation of pySigma through `pipinstall`?

**Comment by thomaspatzke** [comment]
According to search results for the error message this moght be an issue cause by the specific version of pipenv. Please try

- usage of a new pipenv version.
- removing the fragment part starting with # from the URL

**Comment by rpet** [comment]
Thank you for the reply.

Removing from the URL the fragment part starting with `#` yields another error:

```
$ pipenv install git+https://github.com/SigmaHQ/pySigma.git
Installing git+https://github.com/SigmaHQ/pySigma.git…
⠹WARNING: pipenv requires an #egg fragment for version controlled dependencies. Please install remote dependency in the form git+https://github.com/SigmaHQ/pySigma.git#egg=<package-name>.   
```
On the other hand, it seems that both Debian an Ubuntu, even in its latest versions, are stuck in the same ancient version of `pipenv ` (11.9):

- https://packages.debian.org/search?keywords=pipenv
- https://packages.ubuntu.com/search?keywords=pipenv&searchon=names&section=all

So the problem will be the same no matter wich distribution I use. Maybe some RPM-based distibution ships with a newer version of `pipenv`, but I think I will  prefer to install pySigma manually.

**Comment by rpet** [comment]
Despite my previous comment about RPM-based distros I was curious about this problem, so I've tried with a fresh installation of OpenSUSE Tumbleweed and `pipenv 2021.5.29` .

The problem is the same as in Debian without the `#` fragment of the URL ("pipenv requires an #egg fragment..."):

```
> pipenv --version
pipenv, version 2021.5.29
```

```
> pipenv install git+https://github.com/SigmaHQ/pySigma.git#main
Creating a virtualenv for this project...
Pipfile: /home/rpet/Pipfile
Using /usr/bin/python3 (3.8.11) to create virtualenv...
⠏ Creating virtual environment...created virtual environment CPython3.8.11.final.0-64 in 3426ms
  creator CPython3Posix(dest=/home/rpet/.local/share/virtualenvs/rpet-HtsefH42, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/rpet/.local/share/virtualenv)
    added seed packages: pip==20.3.1, setuptools==51.0.0, wheel==0.36.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment!
Virtualenv location: /home/rpet/.local/share/virtualenvs/rpet-HtsefH42
Creating a Pipfile for this project...
Installing git+https://github.com/SigmaHQ/pySigma.git#main...
WARNING: pipenv requires an #egg fragment for version controlled dependencies. Please install remote dependency in the form git+https://github.com/SigmaHQ/pySigma.git#egg=<package-name>.
✘ Installation Failed
```

**Comment by frack113** [comment]
Hello,
get the same trouble on Manjaro Linux.
The `Pipfile` is create but empty
```bash
[frack113@G50 ~]$ cat Pipfile 
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.9"
```

**Comment by frack113** [comment]
Hello,
find this : 
<pre><font color="#4E9A06"><b>frack113@frack113-virtual-machine</b></font>:<font color="#3465A4"><b>~/tets</b></font>$ pipenv install git+https://github.com/SigmaHQ/pySigma.git#egg=pysigma
<b>Installing </b><font color="#4E9A06"><b>git+https://github.com/SigmaHQ/pySigma.git#egg=pysigma</b></font>...
<b>Adding</b> <font color="#4E9A06"><b>pysigma</b></font> <b>to Pipfile&apos;s</b> <font color="#C4A000"><b>[packages]</b></font><b>...</b>
✔ Installation Succeeded 
<b>Pipfile.lock not found, creating...</b>
Locking <font color="#C4A000">[dev-packages]</font> dependencies...
Locking <font color="#C4A000">[packages]</font> dependencies...
Building requirements...
Resolving dependencies...
<font color="#4E9A06">✔ Success!</font> 
<b>Updated Pipfile.lock (96a0a9)!</b>
<b>Installing dependencies from Pipfile.lock (96a0a9)...</b>
  🐍   <font color="#4E9A06"><b>▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉</b></font> 0/0 — <font color="#2E3436">00:00:00</font>
To activate this project&apos;s virtualenv, run <font color="#C4A000">pipenv shell</font>.
Alternatively, run a command inside the virtualenv with <font color="#C4A000">pipenv run</font>.
<font color="#4E9A06"><b>frack113@frack113-virtual-machine</b></font>:<font color="#3465A4"><b>~/tets</b></font>$</pre>

**Comment by rpet** [comment]
@frack113  That worked fine on Debian 11 and Ubuntu 20.04. 

Thank you!
