### ISSUE TITLE
Weird behavior with SigmaRegularExpression.escape(escape_escape_char=False)

### ISSUE THREAD

**Issue by Res260** [SigmaHQ/pySigma#153]
Reading the docstring of `SigmaRegularExpression.escape()`,I don't think this is an intended behavior?

![image](https://github.com/SigmaHQ/pySigma/assets/14599855/d460c7ae-ed8f-4335-ad51-168c015cdcb8)

I'm not sure why it does that, but if I get confirmation that this is unexpected behavior, I can look for a fix :)

**Comment by Res260** [comment]
Fix was pretty simple, see #154

**Comment by thomaspatzke** [comment]
Sure, done! v0.10.7 is waiting for you 😉
