### ISSUE TITLE
Implementation of non-conjunctive format for conditionals in a backend

### ISSUE THREAD

**Issue by ThisIsNotTheUserYouAreLookingFor** [SigmaHQ/pySigma#185]
Hi there! I'm trying to build a backend and a pipeline for Chronicle UDM, since I know there was som sigmacli implementation for it. The problem with UDM is that it enforces non-conjunctive format for boolean expressions, which can't be solved with messing around with precedence. You can see an example in the following test: https://github.com/ThisIsNotTheUserYouAreLookingFor/pySigma-backend-chronicle/blob/main/tests/test_chronicle_backend.py#L58C5-L58C37

Anyone has an idea how I approach this one? I tried overriding the conditional or creation, but it seems a bit more complex than that :)

**Comment by Res260** [comment]
So the language doesn't have an equivalent of `somefield IN ("value1, value2")`?

**Comment by ThisIsNotTheUserYouAreLookingFor** [comment]
There is an "IN" alternative, but not without adding a reference list in a different interface. I requested that feature already though :/

**Comment by ThisIsNotTheUserYouAreLookingFor** [comment]
Alrighty, I found a way around it. There are two languages that can be used: one is using UDM search, which enforces CNF, the other one, YARA-L does not. Explained it on the forums here: https://www.googlecloudcommunity.com/gc/SIEM-Forum/Conjunctive-normative-form-in-UDM-queries-vs-YARA-L/m-p/696645#M458 
I'll work on the YARA-L output first and make that the default. Thanks!
