### ISSUE TITLE
Fieldref missing in SigmaCorrelationCondition to_dict() 

### ISSUE THREAD

**Issue by nzedler** [SigmaHQ/pySigma#198]
Calling to_dict() of the SigmaCorrelationCondition results in only the operator being their (and not "field", which is mandatory for correlation type: value_count).

I found the bug when converting a value_count SigmaCorrelation rule to_dict() and then importing the created dictionary via from_dict(), resulting in a "sigma.exceptions.SigmaCorrelationRuleError: Value count correlation rule without field reference".

**Example:**

```yaml
condition:
    field: User
    gte: 99
```

`SigmaCorrelationCondition.to_dict()` currently results in:
```json
{"gte": 99}
```

It should be:
```json
{"field": "User", "gte": 99}
```

**See https://github.com/SigmaHQ/pySigma/pull/197 for the pull request.**

**Comment by thomaspatzke** [comment]
Thanks for directly providing the fix 👍
