### ISSUE TITLE
Processing pipeline guidance

### ISSUE THREAD

**Issue by kartone** [SigmaHQ/pySigma#216]
Looking for guidance: I wonder how I can create a pipeline yml file that simply drops unsupported fields present the rule that there aren't supported by my backend. For example, Hashes fields is not supported by my telemetry. [This](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_process_hacker.yml) is the rule I'm trying to convert and I want to drop the entire **Hashes** section and **Imphash** fields. Thank you!

This is the pipeline YML file I'm using as command line argument in the sigma convert command.

```name: Drop unsupported fileds
 priority: 100
 transformations:
     # Drops the Hashes field which is specific to Sysmon logs
     - id: hashes_drop_sysmon-specific-field
       type: drop_detection_item
       field_name_conditions:
         - type: include_fields
           fields:
           - Hashes
       rule_conditions:
       - type: logsource
         product: windows
         category: process_creation
```

However it seems not working:

```
sigma convert -t sentinel_one_pq -p s1_pipeline.yml  ../sigma/rules/windows/process_creation/proc_creation_win_pua_process_hacker.yml
Parsing Sigma rules  [####################################]  100%
Error while conversion: Invalid SigmaDetectionItem field name encountered: Hashes. This pipeline only supports the following fields:
{CommandLine}, {Company}, {CurrentDirectory}, {Description}, {DestinationHostname}, {DestinationIp}, {DestinationPort}, {Details}, {Image}, {ImageLoaded}, {Imphash}, {IntegrityLevel}, {OriginalFileName}, {ParentCommandLine}, {ParentImage}, {ParentProcessId}, {PipeName}, {ProcessId}, {Product}, {Protocol}, {Publisher}, {QueryName}, {SourceFilename}, {SourceIp}, {SourcePort}, {TargetFilename}, {TargetObject}, {TerminalSessionId}, {User}, {answer}, {dst_ip}, {dst_port}, {md5}, {query}, {record_type}, {sha1}, {sha256}, {src_ip}, {src_port}
```

**Comment by joshnck** [comment]
This is a problem with the backend and not pySigma - please see this link to the section of code that is supporting that error generation: https://github.com/7RedViolin/pySigma-backend-sentinelone-pq/blob/24123bcba1cc4ee425a55d3ef6b46a64c90109b7/sigma/pipelines/sentinelone_pq/sentinelone_pq.py#L26

**Comment by kartone** [comment]
@joshnck I see. I understand that `translation_dict` is meant to translate field naming, I can't understand how I can discard certain fields. Thanks for your help.

**Comment by joshnck** [comment]
> @joshnck I see. I understand that `translation_dict` is meant to translate field naming, I can't understand how I can discard certain fields. Thanks for your help.

So your pipeline logic is correct but there is an error in the handling of the fields in the backend that is giving you the issue. I'm not sure how you'll approach that with the backend but if you consider your logic mapped to a different backend like Splunk it works as expected:

Check here for an example:
[sigconverter.io](https://sigconverter.io/#backend=splunk&format=default&pipeline=&rule=dGl0bGU6IFBVQSAtIFByb2Nlc3MgSGFja2VyIEV4ZWN1dGlvbgppZDogODExZTAwMDItYjEzYi00YTE1LTlkMDAtYTYxM2ZjZTY2ZTQyCnJlbGF0ZWQ6CiAgICAtIGlkOiA1NzIyZGZmMS00YmRkLTQ5NDktODZhYi1mYmFmNzA3ZTc2N2EKICAgICAgdHlwZTogc2ltaWxhcgpzdGF0dXM6IGV4cGVyaW1lbnRhbApkZXNjcmlwdGlvbjogfAogICAgRGV0ZWN0cyB0aGUgZXhlY3V0aW9uIG9mIFByb2Nlc3MgSGFja2VyIGJhc2VkIG9uIGJpbmFyeSBtZXRhZGF0YSBpbmZvcm1hdGlvbiAoSW1hZ2UsIEhhc2gsIEltcGhhc2gsIGV0YykuCiAgICBQcm9jZXNzIEhhY2tlciBpcyBhIHRvb2wgdG8gdmlldyBhbmQgbWFuaXB1bGF0ZSBwcm9jZXNzZXMsIGtlcm5lbCBvcHRpb25zIGFuZCBvdGhlciBsb3cgbGV2ZWwgb3B0aW9ucy4KICAgIFRocmVhdCBhY3RvcnMgYWJ1c2VkIG9sZGVyIHZ1bG5lcmFibGUgdmVyc2lvbnMgdG8gbWFuaXB1bGF0ZSBzeXN0ZW0gcHJvY2Vzc2VzLgpyZWZlcmVuY2VzOgogICAgLSBodHRwczovL3Byb2Nlc3NoYWNrZXIuc291cmNlZm9yZ2UuaW8vCiAgICAtIGh0dHBzOi8vd3d3LmNyb3dkc3RyaWtlLmNvbS9ibG9nL2ZhbGNvbi1vdmVyd2F0Y2gtcmVwb3J0LWZpbmRzLWluY3JlYXNlLWluLWVjcmltZS8KYXV0aG9yOiBGbG9yaWFuIFJvdGggKE5leHRyb24gU3lzdGVtcykKZGF0ZTogMjAyMi8xMC8xMAptb2RpZmllZDogMjAyMy8xMi8xMQp0YWdzOgogICAgLSBhdHRhY2suZGVmZW5zZV9ldmFzaW9uCiAgICAtIGF0dGFjay5kaXNjb3ZlcnkKICAgIC0gYXR0YWNrLnBlcnNpc3RlbmNlCiAgICAtIGF0dGFjay5wcml2aWxlZ2VfZXNjYWxhdGlvbgogICAgLSBhdHRhY2sudDE2MjIKICAgIC0gYXR0YWNrLnQxNTY0CiAgICAtIGF0dGFjay50MTU0Mwpsb2dzb3VyY2U6CiAgICBjYXRlZ29yeTogcHJvY2Vzc19jcmVhdGlvbgogICAgcHJvZHVjdDogd2luZG93cwpkZXRlY3Rpb246CiAgICBzZWxlY3Rpb25faW1hZ2U6CiAgICAgICAgLSBJbWFnZXxjb250YWluczogJ1xQcm9jZXNzSGFja2VyXycKICAgICAgICAtIEltYWdlfGVuZHN3aXRoOiAnXFByb2Nlc3NIYWNrZXIuZXhlJwogICAgICAgIC0gT3JpZ2luYWxGaWxlTmFtZToKICAgICAgICAgICAgICAtICdQcm9jZXNzSGFja2VyLmV4ZScKICAgICAgICAgICAgICAtICdQcm9jZXNzIEhhY2tlcicKICAgICAgICAtIERlc2NyaXB0aW9uOiAnUHJvY2VzcyBIYWNrZXInCiAgICAgICAgLSBQcm9kdWN0OiAnUHJvY2VzcyBIYWNrZXInCiAgICBzZWxlY3Rpb25faGFzaGVzOgogICAgICAgIEhhc2hlc3xjb250YWluczoKICAgICAgICAgICAgLSAnTUQ1PTY4RjlCNTI4OTVGNEQzNEU3NDExMkYzMTI5QjNCMDBEJwogICAgICAgICAgICAtICdNRDU9QjM2NUFGMzE3QUU3MzBBNjdDOTM2RjIxNDMyQjlDNzEnCiAgICAgICAgICAgIC0gJ1NIQTE9QTBCREZBQzNDRTE4ODBCMzJGRjlCNjk2NDU4MzI3Q0UzNTJFM0IxRCcKICAgICAgICAgICAgLSAnU0hBMT1DNUUyMDE4QkY3QzBGMzE0RkVENEZEN0ZFN0U2OUZBMkU2NDgzNTlFJwogICAgICAgICAgICAtICdTSEEyNTY9RDRBMEZFNTYzMTZBMkM0NUI5QkE5QUMxMDA1MzYzMzA5QTNFREM3QUNGOUU0REY2NEQzMjZBMEZGMjczRTgwRicKICAgICAgICAgICAgLSAnU0hBMjU2PUJEMkMyQ0YwNjMxRDg4MUVEMzgyODE3QUZDQ0UyQjA5M0Y0RTQxMkZGQjE3MEE3MTlFMjc2MkYyNTBBQkZFQTQnCiAgICAgICAgICAgIC0gJ0lNUEhBU0g9MzY5NTMzM0M2MERFREVDRENBRkYxNTkwNDA5QUE0NjInCiAgICAgICAgICAgIC0gJ0lNUEhBU0g9MDRERTBBRDlDMzdFQjdCRDUyMDQzRDJFQ0FDOTU4REYnCiAgICBzZWxlY3Rpb25faGFzaF92YWx1ZXM6CiAgICAgICAgLSBtZDU6CiAgICAgICAgICAgICAgLSAnNjhmOWI1Mjg5NWY0ZDM0ZTc0MTEyZjMxMjliM2IwMGQnCiAgICAgICAgICAgICAgLSAnYjM2NWFmMzE3YWU3MzBhNjdjOTM2ZjIxNDMyYjljNzEnCiAgICAgICAgLSBzaGExOgogICAgICAgICAgICAgIC0gJ2M1ZTIwMThiZjdjMGYzMTRmZWQ0ZmQ3ZmU3ZTY5ZmEyZTY0ODM1OWUnCiAgICAgICAgICAgICAgLSAnYTBiZGZhYzNjZTE4ODBiMzJmZjliNjk2NDU4MzI3Y2UzNTJlM2IxZCcKICAgICAgICAtIHNoYTI1NjoKICAgICAgICAgICAgICAtICdkNGEwZmU1NjMxNmEyYzQ1YjliYTlhYzEwMDUzNjMzMDlhM2VkYzdhY2Y5ZTRkZjY0ZDMyNmEwZmYyNzNlODBmJwogICAgICAgICAgICAgIC0gJ2JkMmMyY2YwNjMxZDg4MWVkMzgyODE3YWZjY2UyYjA5M2Y0ZTQxMmZmYjE3MGE3MTllMjc2MmYyNTBhYmZlYTQnCiAgICAgICAgLSBJbXBoYXNoOgogICAgICAgICAgICAgIC0gJzA0ZGUwYWQ5YzM3ZWI3YmQ1MjA0M2QyZWNhYzk1OGRmJwogICAgICAgICAgICAgIC0gJzM2OTUzMzNjNjBkZWRlY2RjYWZmMTU5MDQwOWFhNDYyJwogICAgY29uZGl0aW9uOiAxIG9mIHNlbGVjdGlvbl8qCmZhbHNlcG9zaXRpdmVzOgogICAgLSBXaGlsZSBzb21ldGltZXMgJ1Byb2Nlc3MgSGFja2VyIGlzIHVzZWQgYnkgbGVnaXRpbWF0ZSBhZG1pbmlzdHJhdG9ycywgdGhlIGV4ZWN1dGlvbiBvZiBQcm9jZXNzIEhhY2tlciBtdXN0IGJlIGludmVzdGlnYXRlZCBhbmQgYWxsb3dlZCBvbiBhIGNhc2UgYnkgY2FzZSBiYXNpcwpsZXZlbDogbWVkaXVt&pipelineYml=IHByaW9yaXR5OiAxMDAKIHRyYW5zZm9ybWF0aW9uczoKICAgICAjIERyb3BzIHRoZSBIYXNoZXMgZmllbGQgd2hpY2ggaXMgc3BlY2lmaWMgdG8gU3lzbW9uIGxvZ3MKICAgICAtIGlkOiBoYXNoZXNfZHJvcF9zeXNtb24tc3BlY2lmaWMtZmllbGQKICAgICAgIHR5cGU6IGRyb3BfZGV0ZWN0aW9uX2l0ZW0KICAgICAgIGZpZWxkX25hbWVfY29uZGl0aW9uczoKICAgICAgICAgLSB0eXBlOiBpbmNsdWRlX2ZpZWxkcwogICAgICAgICAgIGZpZWxkczoKICAgICAgICAgICAtIEhhc2hlcwogICAgICAgcnVsZV9jb25kaXRpb25zOgogICAgICAgLSB0eXBlOiBsb2dzb3VyY2UKICAgICAgICAgcHJvZHVjdDogd2luZG93cwogICAgICAgICBjYXRlZ29yeTogcHJvY2Vzc19jcmVhdGlvbg%3D%3D)

**Comment by kartone** [comment]
Ok. Indeed I've re-mapped the `OriginalFileName` to another supported field within my local backend source code. Still, the backend is unable to follow the pipeline. Should I fire an issue on its repo?

**Comment by thomaspatzke** [comment]
I have two answers for you 😉

The first one is: don't do this! It's strongly discouraged to just drop parts of the rule that are not supported by the targeted backend or data model. The reason is that dropping parts of the detection changes its intended logic, which results in:

* more false positives if the dropped conditions are AND-linked, the *good* case. Or
* false negatives also known as *the false sense of security* if the dropped conditions are OR-linked, which is the worse case.

In the case of the rule you referred the worse case will happen. The detection can be better bypassed by attackers.

The possibility for processing pipelines to raise errors in such cases was introduced in pySigma to warn the users of it or tools based on it about this fact. In Sigma CLI you can use `--skip-unsupported` to skip over such rules.

The second answer is: if you know what you're doing and want to do it anyways, you should use the `drop_detection_item` transformation together with an `include_field_condition` similar to [this part of the CrowdStrike processing pipeline](https://github.com/SigmaHQ/pySigma-pipeline-crowdstrike/blob/4be9082f679f2a45e97d136175ef5ec857c17d1a/sigma/pipelines/crowdstrike/crowdstrike.py#L78).

**Comment by kartone** [comment]
Hey @thomaspatzke, thanks for your reply. I'm aware of the downsides of doing this and, as of now, this project is into its first experimental phase. I'm going to use SentinelOne that does not support imphash anyway.

> The second answer is: if you know what you're doing and want to do it anyways, you should use the `drop_detection_item` transformation together with an `include_field_condition` similar to [this part of the CrowdStrike processing pipeline](https://github.com/SigmaHQ/pySigma-pipeline-crowdstrike/blob/4be9082f679f2a45e97d136175ef5ec857c17d1a/sigma/pipelines/crowdstrike/crowdstrike.py#L78).

Based on you advice, I modified the pipeline [like this](https://github.com/kartone/pySigma-backend-sentinelone-pq/blob/6dfd273c285232eda7a0057b49d08cc854d8c7e5/sigma/pipelines/sentinelone_pq/sentinelone_pq.py#L228) but still it stucks when it encounter **Imphash** field. Can you please advice? Many thanks.
