### ISSUE TITLE
add_condition processing object not acting as expected

### ISSUE THREAD

**Issue by joshnck** [SigmaHQ/pySigma#217]
[sigconverter.io debugging test](https://beta.sigconverter.io/#backend=splunk&format=default&pipeline=&rule=dGl0bGU6IHRlc3RpbmdfY29uZGl0aW9ucwppZDogODExZTAwMDItYjEzYi00YTE1LTlkMDAtYTYxM2ZjZTY2ZTQyCnN0YXR1czogZXhwZXJpbWVudGFsCmRlc2NyaXB0aW9uOiBkZXNjcmlwdGlvbgpyZWZlcmVuY2VzOgogICAgLSB0ZXN0CmF1dGhvcjogdGVzdApkYXRlOiAyMDI0LzA1LzAzCnRhZ3M6CiAgICAtIGF0dGFjay5kZWZlbnNlX2V2YXNpb24KbG9nc291cmNlOgogICAgY2F0ZWdvcnk6IHByb2Nlc3NfY3JlYXRpb24KICAgIHByb2R1Y3Q6IHdpbmRvd3MKZGV0ZWN0aW9uOgogICAgc2VsZWN0aW9uX2ltYWdlOgogICAgICAgIC0gdGVzdDF8Y29udGFpbnM6ICdcdGVzdDFfdmFsdWUnCiAgICAgICAgLSB0ZXN0Mnxjb250YWluczogJ1x0ZXN0Ml92YWx1ZScKICAgICAgICAtIHRlc3QzfGNvbnRhaW5zOiAnXHRlc3QzX3ZhbHVlJwogICAgY29uZGl0aW9uOiAxIG9mIHNlbGVjdGlvbl8qCmZhbHNlcG9zaXRpdmVzOgogICAgLSBVbmtub3duCmxldmVsOiBjcml0aWNhbA%3D%3D&pipelineYml=Cm5hbWU6IGNyb3dkc3RyaWtlCnByaW9yaXR5OiAxMAp0cmFuc2Zvcm1hdGlvbnM6CgojIyMjIElOREVYIEFORCBPUyBBU1NJR05NRU5UUwogIC0gaWQ6IHJ1bGVfY29uZF90ZXN0CiAgICB0eXBlOiBhZGRfY29uZGl0aW9uCiAgICBjb25kaXRpb25zOgogICAgICBydWxlX2NvbmRfdGVzdDogInJ1bGVfY29uZF90ZXN0IgogICAgcnVsZV9jb25kaXRpb25zOgogICAgICAtIHR5cGU6IGNvbnRhaW5zX2RldGVjdGlvbl9pdGVtCiAgICAgICAgZmllbGQ6ICJub24tZXhpc3RlbnQiCiAgICAgICAgdmFsdWU6ICIiCiAgICBkZXRlY3Rpb25faXRlbV9jb25kX25vdDogZmFsc2UKICAgIHJ1bGVfY29uZF9ub3Q6IHRydWUKICAgIGZpZWxkX25hbWVfY29uZF9ub3Q6IGZhbHNlCiAgICAKCiAgLSBpZDogZmllbGRfbmFtZV9jb25kX3Rlc3QKICAgIHR5cGU6IGFkZF9jb25kaXRpb24KICAgIGNvbmRpdGlvbnM6CiAgICAgIGZpZWxkX25hbWVfY29uZF90ZXN0OiAiZmllbGRfbmFtZV9jb25kX3Rlc3QiCiAgICBmaWVsZF9uYW1lX2NvbmRpdGlvbnM6CiAgICAgIC0gdHlwZTogaW5jbHVkZV9maWVsZHMKICAgICAgICBmaWVsZHM6ICJub24tZXhpc3RlbnQiCiAgICBkZXRlY3Rpb25faXRlbV9jb25kX25vdDogZmFsc2UKICAgIHJ1bGVfY29uZF9ub3Q6IGZhbHNlCiAgICBmaWVsZF9uYW1lX2NvbmRfbm90OiB0cnVlCiAgICAKICAtIGlkOiBkZXRlY3Rpb25faXRlbV9jb25kX3Rlc3QKICAgIHR5cGU6IGFkZF9jb25kaXRpb24KICAgIGNvbmRpdGlvbnM6CiAgICAgIGRldGVjdGlvbl9pdGVtX3Rlc3Q6ICJkZXRlY3Rpb25faXRlbV9jb25kX3Rlc3QiCiAgICBkZXRlY3Rpb25faXRlbV9jb25kaXRpb25zOgogICAgICAtIHR5cGU6IHByb2Nlc3NpbmdfaXRlbV9hcHBsaWVkCiAgICAgICAgcHJvY2Vzc2luZ19pdGVtX2lkOiAnZmllbGRfbmFtZV9jb25kX3Rlc3QnCiAgICBkZXRlY3Rpb25faXRlbV9jb25kX25vdDogdHJ1ZQogICAgcnVsZV9jb25kX25vdDogZmFsc2UKICAgIGZpZWxkX25hbWVfY29uZF9ub3Q6IGZhbHNlCgoKcG9zdHByb2Nlc3Npbmc6Ci0gdHlwZTogdGVtcGxhdGUKICB0ZW1wbGF0ZTogfCsKICAgIFt7eyBxdWVyeSB9fV0KICAgIAogICAgCiAgICBbe3sgcGlwZWxpbmUgfX1dCg%3D%3D)

I expect the `add_condition` object to be able to be negated by any of the 3 conditions used by pySigma - but as you can see in my example it only works with the `rule_conditions` type. Each of the 3 conditions result in a `False` statement and thus the `key:value` pairs should disappear from the final query - but `detection_item_test` and `field_name_cond_test` are still present. 

The expected behavior is that toggling the negation from "false" to "true" for the matching condition type would make `add_condition` not apply.

**Comment by thomaspatzke** [comment]
That's a case of *works as designed* 😉 The reason for this is that `add_condition` is a transformation that works on the whole rule and detection item and field name conditions aren't evaluated for such transformations. Detection item conditions are only evaluated for detection item or field mapping transformations. Field name conditions are also evaluated in the rule field list and for field name references in values. I've [improved the documentation and described this behavior more explicit](https://sigmahq-pysigma.readthedocs.io/en/latest/Processing_Pipelines.html#conditions).

If you want to check for the existence of specific detection items (or their non-existence via negation) at rule level, use the [`contains_detection_item` condition](https://sigmahq-pysigma.readthedocs.io/en/latest/Processing_Pipelines.html#sigma.processing.conditions.RuleContainsDetectionItemCondition).
