### ISSUE TITLE
Missing condition check in pipelines / ProcessingItem

### ISSUE THREAD

**Issue by bast00** [SigmaHQ/pySigma#219]
Hi !

I have a very basic transform, to print an error when some fields are found in product-specific sigmas :

```
ProcessingItem(
                identifier="my_identifier",
                transformation=RuleFailureTransformation(
                    message="my mesage"
                ),
                field_name_conditions=[
                    IncludeFieldCondition(type="re", fields=["^a\.regex.*$"]),
                ],
                rule_conditions=[
                    LogsourceCondition(product="myproduct"),
                ]
            )
```

But this transform always print an error. The condition is always True.

After digging, I think the condition in the `ProcessingItem.apply()` function is incomplete
 https://github.com/SigmaHQ/pySigma/blob/2d46724218876b9de8dd28e5b407b87dd8fe766c/sigma/processing/pipeline.py#L245

Best regards,
Bast

**Comment by thomaspatzke** [comment]
No, it's because its a `RuleFailureTransformation`. For rule transformations field name conditions are not evaluated. Please use the `DetectionItemFailureTransformation`.

**Comment by thomaspatzke** [comment]
Yes, technically the pipeline checks rule conditions for the transformation at the location you've already discovered while detection item conditions are [checked from the transformation](https://github.com/SigmaHQ/pySigma/blob/2d46724218876b9de8dd28e5b407b87dd8fe766c/sigma/processing/transformations.py#L122) by usage of the [`match_detection_item` method](https://github.com/SigmaHQ/pySigma/blob/2d46724218876b9de8dd28e5b407b87dd8fe766c/sigma/processing/pipeline.py#L253) from the `ProcessingItem` class. Field name conditions [are handled similarly](https://github.com/SigmaHQ/pySigma/blob/2d46724218876b9de8dd28e5b407b87dd8fe766c/sigma/processing/transformations.py#L159) with the [`match_field_name` method](https://github.com/SigmaHQ/pySigma/blob/2d46724218876b9de8dd28e5b407b87dd8fe766c/sigma/processing/pipeline.py#L280).
