### ISSUE TITLE
Sigma accepting malformed yaml in SigmaDetectionItem fields

### ISSUE THREAD

**Issue by twpZero** [SigmaHQ/pySigma#225]
According to [https://yaml.org/spec/1.2.2/](https://yaml.org/spec/1.2.2/#chapter-1-introduction-to-yaml) : 
"[colons](https://yaml.org/spec/1.2.2/#flow-mappings) separate [key/value pairs](https://yaml.org/spec/1.2.2/#mapping)"

However `SigmaDetectionItem.from_mapping` currently allows field to contain ':' .
Currently,  _SigmaDetectionItem.field_ allows keys such as `field:modifier:` without raising any errors.

**Remark**: ':' can also be a reserved char for some backends that work with `key:value` syntax.
That would be increasing the chance of errors in backend despite Sigma Validation.

-> The proposed solution simply check if `field` contains ':'  and raise **SigmaDetectionError**.

Please feel free to accept merge request #224 or to implement your own checks.

**Comment by thomaspatzke** [comment]
Colons are allowed in YAML keys if the [key is quoted](https://yaml.org/spec/1.2.2/#double-quoted-style).
