### ISSUE TITLE
[Question] Rule as dict with only strings

### ISSUE THREAD

**Issue by b2az** [SigmaHQ/pySigma#23]
Hi Thomas,

Sorry to bother you again.
I totally want to shift to this new parser but some things are still hard to understand for me.
Within the "old" converter i did something like the following, to have my detection rules converted to json and then sent to an memcached instance.

```python
import json
from sigma.parser.collection import SigmaCollectionParser
from pymemcache.client.base import Client
parser = SigmaCollectionParser(open(filename,'r').read())
for detection in parser:
    client.set(detection["id"], json.dumps(detection))
```

Do you have some hints, of how i could achieve this with the pySigma version?

Thanks in advance & also thx for your hard work, which makes our lifes easier!

Best,
b2az

**Comment by thomaspatzke** [comment]
It took a while because there were far more corner cases and challenges to solve, but here it is: `SigmaRule.to_dict()`.
