### ISSUE TITLE
FieldnameLogsourceValidator fails with Correlation rules

### ISSUE THREAD

**Issue by Res260** [SigmaHQ/pySigma#239]
I don't have time to fix it, but the FieldnameLogsourceValidator should ignore correlation rules, because we dont want to `sigma check` for correlation rules separately: 

![image](https://github.com/user-attachments/assets/f3ba52a9-b943-4dde-bcfa-3acf0849da9f)

I'll put it in my sigma check validation config to ignore it in the meantime.

**Comment by thomaspatzke** [comment]
Thanks for the issue, just fixed it!
