### ISSUE TITLE
Class CompareOperators is private

### ISSUE THREAD

**Issue by Res260** [SigmaHQ/pySigma#264]
Hello, I was trying to do a condition on a `CompareOperators` object, but I cannot import it:

![image](https://github.com/user-attachments/assets/8ad03b16-d442-4552-997e-f57a2f50ce87)

Since `CompareOperators` is inside the `SigmaCompareExpression` class, it is private and we cannot import it:

![image](https://github.com/user-attachments/assets/dad24d41-8fbc-41d4-b9cd-add0070938f4)

Is there a problem with putting it outside the class so we can import it?

**Comment by thomaspatzke** [comment]
This should be fine or you access it with `SigmaCompareExpression.CompareOperators.<OP>`.

**Comment by thomaspatzke** [comment]
Changed it! Because it's a breaking change and I plan to do some of them for pySigma 1.0 it will be released with 1.0.
