### ISSUE TITLE
ModuleNotFoundError: No module named 'pysigma'

### ISSUE THREAD

**Issue by honi-at-simspace** [SigmaHQ/pySigma#265]
When I originally installed pysigma using `pip install pysigma`, I expected to import it using `import pysigma`.  Indeed, `pysigma-0.11.10.dist-info` was created in `/usr/local/lib/python3.10/dist-packages`.  However, `pysigma` was not created. Instead `sigma` was created. It seems that you are suggesting using `import sigma` and `from sigma.rule import SigmaRule` for example.  This is not explicitly mentioned on your documentation (https://sigmahq-pysigma.readthedocs.io/en/latest/) or in this repo Readme (https://github.com/SigmaHQ/pySigma/blob/main/README.md). 

 Indeed, when I was trying to debug it with Gemini, Gemini said: 

"  
It's unlikely that `!pip install pysigma` installs a package that needs to be imported with `import sigma`.  
Here's why:  
Package Naming Conventions: Python packages typically follow naming conventions that reflect their import names. If you install a package called "pysigma", it's almost certain that you import it using `import pysigma`.  
"

I think my main request is that the documentation be a lot clearer, and there be a lot more explicit explanation that this package is installed via `pip install pysigma` but is imported via `import sigma`.

**Comment by thomaspatzke** [comment]
Thanks for pointing this out. The package name `sigma` is now mentioned on the main page of the docs.

**Comment by nickthelegend** [comment]
The same issue arises with the version 0.11.19

![Image](https://github.com/user-attachments/assets/c2b548fc-a120-41ac-a395-5f42371173ec)
pysigma was not created i expect it to install the module,  but is imported via import sigma
