### ISSUE TITLE
strict version dependency on packaging makes dependency conflicts when installing with other libraries

### ISSUE THREAD

**Issue by honi-at-simspace** [SigmaHQ/pySigma#271]
I want to install `pysigma` in a python environment that has other libraries as well.  Many times, `pip` fails to install with messages like:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pysigma 0.10.10 requires packaging<23.0,>=22.0, but you have packaging 24.1 which is incompatible.
```

Is there any way to relax `pysigma`'s version limitations for `packaging` dependency?

**Comment by honi-at-simspace** [comment]
In particular, several other libraries require `packaging>=23.2`

**Comment by thomaspatzke** [comment]
Which pySigma do you have? The current version depends on packaging >=24.1:

```python
packaging = "^24.1"
```

**Comment by honi-at-simspace** [comment]
I see, I am stuck on `0.10.10` because of another package.  Thank you for your help.
