### ISSUE TITLE
Could not compile rule

### ISSUE THREAD

**Issue by TheDudeasap** [SigmaHQ/pySigma#279]
hi i have an error and dont understand it can someone help me pls ? 

{
  "Module": "Sigma",
  "aurora_eventid": 95,
  "error": "syntax error in selection element of rule Process Deletion of Its Own Executable: invalid Modifier \"fieldref\"",
  "file": "public\\windows\\file\\file_delete\\file_delete_win_delete_own_image.yml",
  "id": "f01d1f70-cd41-42ec-9c0b-26dd9c22bf29",
  "level": "error",
  "msg": "Could not compile rule",
  "time": "2024-09-27T20:16:55+02:00",
  "title": "Process Deletion of Its Own Executable",
  "_Match": [
    "-"
  ],
  "_Description": []
}

**Comment by nasbench** [comment]
This is an aurora error and is unrelated to pysigma.
Aurora currently doesn't support the latest modifiers. This will be resolved soon via an update in the coming days/week.

Thanks.
