### ISSUE TITLE
SigmaReplaceString transformation discards placeholders

### ISSUE THREAD

**Issue by xavigu42** [SigmaHQ/pySigma#284]
Hi guys,

Unsure if this is the right repo or I'd need to open an issue with pySigma directly. I apologize in advance.

https://sigmahq.io/docs/basics/modifiers.html#expand

We were testing the use of the `expand` modifier to make our rules a bit more generic and to ease the maintenance. This would be beneficial for the many DNS/network rules we have at the moment to monitor RRM tools, exfiltration to cloud storage services, etc..

At the moment we need to copy and paste the list of browser binaries in the filters.

I our setup we have observed the following behavior....

What works:

```
QueryName|expand: "%dodgy_websites%"
```

What doesn't work:
```
Image|expand: "%browser_binaries%"
```

**Comment by thomaspatzke** [comment]
Fixed - will get into next release. Verified that CrowdStrike issue is fixed as well, will update it too.
