### ISSUE TITLE
Support for pyparsing > 3.0.0

### ISSUE THREAD

**Issue by fabaff** [SigmaHQ/pySigma#32]
Currently, `pyparsing` is constraint to [`<3.0.0,>=2.4.7`](https://github.com/SigmaHQ/pySigma/blob/4c523654e2a8c68db00de951f8f921e325488273/pyproject.toml#L24).

Are there plans to support `pyparsing` > 3.0.0? Thanks

**Comment by thomaspatzke** [comment]
Just migrated it to ^3.0.7.
