### ISSUE TITLE
Support for pyyaml > 6

### ISSUE THREAD

**Issue by fabaff** [SigmaHQ/pySigma#33]
Currently, `pyyaml` is constraint to [`<6`](https://github.com/SigmaHQ/pySigma/blob/4c523654e2a8c68db00de951f8f921e325488273/pyproject.toml#L23). Most distributions 

Are there plans to support `pyyaml` >= 6? Thanks

**Comment by thomaspatzke** [comment]
Yes, just updated it!

**Comment by fabaff** [comment]
Thank you
