### ISSUE TITLE
Is `|all` modifier correctly supported ?

### ISSUE THREAD

**Issue by gaelmuller** [SigmaHQ/pySigma#38]
Hello,

I'm currently trying to move some existing code we have from `sigmatools` to `pySigma`. I'm enjoying the cleaner design and the new modifiers but I am also wondering if the `|all` modifier is currently correctly supported.

When looking at the `Backend` and `TextQueryBackend`, I'm seeing no reference to the `value_linking` property set by the `|all` modifier. Is this a mistake ?

To fix this in my code, I took the following approach. Does this look right to you ?

```python
if node.parent.value_linking == ConditionOR:
  return any(map(my_func, node.value))
elif node.parent.value_linking == ConditionAND:
  return all(map(my_func, node.value))
```

`node` is of type `ConditionFieldValueInExpression`

**Comment by thomaspatzke** [comment]
Indeed, the handling of all-modified values is wrong in the case where a value list that contains only plain values is converted into a *value in list* expression [at this location](https://github.com/SigmaHQ/pySigma/blob/382e1d0b37c12bd35b841239ad89609fb92a7621/sigma/rule.py#L281). The condition doesn't takes the value linking into account. 

For the else case, the SigmaDetectionItem is expanded into the condition class stored in `value_linking` in the post processing stage of rule parsing, [here](https://github.com/SigmaHQ/pySigma/blob/382e1d0b37c12bd35b841239ad89609fb92a7621/sigma/rule.py#L284) and [few lines later again](https://github.com/SigmaHQ/pySigma/blob/382e1d0b37c12bd35b841239ad89609fb92a7621/sigma/rule.py#L289).

I've fixed the issue by adding the condition to the special case and added tests for these cases. Thanks for pointing this out!
