### ISSUE TITLE
No module named 'attr'

### ISSUE THREAD

**Issue by elhoim** [SigmaHQ/pySigma#42]
I am ggeting the following error:
` File "/home/elhoim/Dropbox/projects/1022.pysigma-to-splunk-converter/venv-linux/lib/python3.8/site-packages/sigma/conversion/base.py", line 3, in <module>
    from attr import field
ModuleNotFoundError: No module named 'attr'
`
About the line 
**from attr import field** 
introduced in https://github.com/SigmaHQ/pySigma/commit/95bdec2c7109b165febef5644a34e7195af3d71f

When removing i do not have an error anymore.
My IDE tells me it is not used.

Versions of libraries installed is latest for everything:
![image](https://user-images.githubusercontent.com/178521/165530663-e9a43d64-33f2-41e5-b697-f509f7a189bb.png)

Should i submit a PR for a change or would it break something?

**Comment by thomaspatzke** [comment]
Thanks for the fix! It was an accidental auto-import, therefore not required.
