### ISSUE TITLE
Getting the components of converted rule. 

### ISSUE THREAD

**Issue by jonathan-s** [SigmaHQ/pySigma#57]
Given a converted detection like this. 

```
EventID="1" CommandLine="*DllRegisterServer*" Image="*rundll32.exe" EventID="1" (CommandLine IN ("*--full*", "*--fast*", 
"*--multiproc*", "*--nomimikatz*", "*--nonet*", "*--path*", "*--target*", "*--append*", "*--norename*", "*--greetings*", 
"*--samba*", "*--killrdp*")) EventID="11" (TargetFilename IN ("*RECOVER-FILES.txt", "*.lnk")) Image="*rundll32.exe"
```

I would like to be able to access each of the names in a format something like this. 

```
[
  {"name": "EventID", "search": 'EventID="1"'},
  {"name": "CommandLine", "search": 'CommandLine="*DllRegisterServer*"'},
  {"name": "CommandLine", "search": '(CommandLine IN ("*--full*", "*--fast*", 
"*--multiproc*", "*--nomimikatz*", "*--nonet*", "*--path*", "*--target*", "*--append*", "*--norename*", "*--greetings*", 
"*--samba*", "*--killrdp*"))'}
  ...
]
```

**Comment by nNipsx-Sec** [comment]
The output when convert rules depend on backend support format; Now pysigma just support few SIEM output format.
So if you want to specific output; maybe you need to build new backend for you.

**Comment by thomaspatzke** [comment]
This seems quite special for me. I think this could be implemented for a specific backend by extending the class and hooking into the appropriate methods like `convert_condition_field_eq_val_str` to intercept the output and output something like you want. Generally there are no plans to implement such format on pySigma level, as it requires lots of changes that would make the code more complex (I guess) for quite special requirements.
