### ISSUE TITLE
pySigma/sigma-cli Elastic Rule Conversions

### ISSUE THREAD

**Issue by mshapiro17** [SigmaHQ/pySigma#58]
I was attempting to use pySigma and sigma-cli to convert sigma rules to EQL rules, but when running the sigma-convert command with the -t es-rule-eql argument that worked for sigmac and was noted in the pySigma readme, it told me that the only valid values for -t were splunk, insightidr, and qradar. Am I missing something, or does pySigma not support EQL?

**Comment by Neo23x0** [comment]
Yes, you're right. It doesn't support EQL yet. @thomaspatzke is working on it.

**Comment by mshapiro17** [comment]
Good to know, thanks!

**Comment by eliranDream** [comment]
Hi @thomaspatzke 
I see that currently there is only support for DSL query, there are plans to also support EQL ?
