### ISSUE TITLE
Case sensitive condition conversion issues

### ISSUE THREAD

**Issue by joshnck** [SigmaHQ/pySigma#63]
I wrote a detection that was using `condition: selection AND NOT filter` and I was getting a mysterious EOF error message. Editing the statement to be `condition: selection and not filter` fixed the issue.

It was an interesting bug because the converter, on the other end, changes the `not` to `NOT`. In this case I do not believe it should be case sensitive.

**Comment by thomaspatzke** [comment]
Can you please describe more concretely where the converter changed the casing? Generally, the boolean operators in Sigma rules should be lower-cased.

**Comment by joshnck** [comment]
```
 python generator.py '{}' "['../../itsec-sigma/rules/custom/m365/microsoft365_malware_detected_in_cloud_storage.yml']" "."
{'searches': {'Endpoint - (Sigma) Potential malware detected in cloud storage - Rule': {'description': 'Alert when O365 detects malware in OneDrive cloud storage using their AV analysis', 'action.correlationsearch.annotations': '{"mitre_attack":[],"kill_chain_phases":["execution", "persistence"],"Sigma":["bc0e354b-e35d-4f7e-8929-d6450557acaf"], "Author": ["Josh Nickels"], "References": ["https://learn.microsoft.com/en-us/defender-cloud-apps/anomaly-detection-policy"]}', 'action.correlationsearch.label': '(Sigma) Potential malware detected in cloud storage', 'action.notable.param.rule_title': '(Sigma) Potential malware detected in cloud storage', 'action.notable.param.rule_description': 'Alert when O365 detects malware in OneDrive cloud storage using their AV analysis', 'action.notable.param.next_steps': '{"version": "1", "data": [\'_False Positives:_- Non-malicious file or False Positive file detection by Microsoft\']}', 'action.notable.param.security_domain': 'endpoint', 'action.notable.param.severity': 'high', 'dispatch.earliest_time': '-2h', 'dispatch.latest_time': 'now', 'cron_schedule': '06 1-23/2 * * *', 'disabled': 'false', 'alert.suppress': 1, 'alert.suppress.fields': 'host', 'search': 'index="*_azure_audit" workload="SecurityComplianceCenter" name="Malware detection" ResultStatus="Succeeded" NOT data="*<my filter>*"'}}}
```

Here is the output of generator.py that I mentioned. In this instance I was able to get it to compile by modifying the `condition:` field in the Sigma rule to: `condition: selection and not filter` whereas I previously had it at `condition: selection AND NOT filter` and I got the EOF error message. I can provide the error message too if you'd like!

**Comment by thomaspatzke** [comment]
That's expected behavior: pySigma only accepts small-cased boolean operators as [implemented here](https://github.com/SigmaHQ/pySigma/blob/main/sigma/conditions.py#L195). The EOF error is caused by the parser because upper-cased operators are parsed as identifiers. Surely something that can be improved.

A converter generates a query in a language that is not a Sigma condition. Therefore the resulting syntax has no meaning for the Sigma condition. It's something different.

**Comment by joshnck** [comment]
Thanks for clearing that up!
