### ISSUE TITLE
Error creating SigmaRule/SigmaCollection from yaml file ('str' object has no attribute 'get')

### ISSUE THREAD

**Issue by GeorgiNikolovRMA** [SigmaHQ/pySigma#68]
Hello,

I have just started to play around with the sigma rules using pysigma. I installed it via pip and was trying to parse a simple rule (some proxy rules from the github repo), but every time I get an error: "AttributeError: 'str' object has no attribute 'get'".

![Screenshot from 2022-10-20 10-32-21](https://user-images.githubusercontent.com/22518848/196898322-6c05a851-e339-4625-9dd1-f7d049e030c4.png)

I just tried to follow the examples shown in https://sigmahq-pysigma.readthedocs.io/en/latest/ . 

The rules that I used to test are:
- https://github.com/SigmaHQ/sigma/blob/master/rules/proxy/proxy_adv_ip_port_scanner_upd_check.yml
- https://github.com/SigmaHQ/sigma/blob/master/rules/proxy/proxy_apt40.yml

**Comment by GeorgiNikolovRMA** [comment]
Hello, I did manage to load the rule. I had to open it as a yaml file beforehand and then pass it to SigmaRule_from_yaml :)
Thank you for the help.

**Comment by thomaspatzke** [comment]
Great, thanks to @jabrcks for providing the answer!
