### ISSUE TITLE
How to trigger some specific backend functions?

### ISSUE THREAD

**Issue by vandir** [SigmaHQ/pySigma#78]
I'm writing a custom backend but there are three functions which I don't understand how to trigger. These functions are:

- convert_condition_field_eq_query_expr
- convert_condition_query_expr
- convert_condition_val_re

Can you please provide a sample Sigma rule that needs to invoke those functions to be correctly converted?

**Comment by thomaspatzke** [comment]
> * convert_condition_field_eq_query_expr

This is called in the special case when equalness of a field to a `SigmaQueryExpression` object should be converted to a query. A [`SigmaQueryExpression`](https://github.com/SigmaHQ/pySigma/blob/8d42c594cd139dbe706faca5f74e6bd189a5f68e/sigma/types.py#L573) basically means that a raw query that was defined in a processing pipeline by a [`QueryExpressionPlaceholderTransformation`](https://sigmahq-pysigma.readthedocs.io/en/latest/Processing_Pipelines.html#sigma.processing.transformations.QueryExpressionPlaceholderTransformation) is used as replacement for a placeholder. This is usually only needed if your backend supports querying lookup as Splunk does. Check [this test](https://github.com/SigmaHQ/pySigma/blob/8d42c594cd139dbe706faca5f74e6bd189a5f68e/tests/test_conversion_base.py#L385) for an example.

> * convert_condition_query_expr

This is almost the same as the previous method, but not bound to a field. Check [this test case](https://github.com/SigmaHQ/pySigma/blob/8d42c594cd139dbe706faca5f74e6bd189a5f68e/tests/test_conversion_base.py#L405) for an example.

> * convert_condition_val_re

This is for regular expression mapping not bound to a field. Often there is some kind of meta-field that can be used to match the whole event. Check [this test case](https://github.com/SigmaHQ/pySigma/blob/8d42c594cd139dbe706faca5f74e6bd189a5f68e/tests/test_conversion_base.py#L440) for an example.

**Comment by vandir** [comment]
Thanks, perfectly clear.
