### ISSUE TITLE
"Modifier SigmaRegularExpressionModifier incompatible" when converting re

### ISSUE THREAD

**Issue by barvhaim** [SigmaHQ/pySigma#79]
When trying to convert a rule that includes `field|re` I am able to do the translation only if there is no pipeline that transform the field, if there is a mapping transformation for that field - I get an error `Error while conversion: Modifier SigmaRegularExpressionModifier incompatible to value type of 'SigmaRegularExpression(regexp='foo.*bar')'`.

Is that the expected behavior? What am I missing?

**Comment by barvhaim** [comment]
@thomaspatzke I am talking about a transformed field (like after field mapping), when it goes thru the field mapping pipeline I get this issue. Not sure we are talking about the same thing.

**Comment by thomaspatzke** [comment]
Ok, it appears that the re modifier is applied twice. I'm wondering how this differs from [this test case](https://github.com/SigmaHQ/pySigma/blob/4e042c9bdfda2c2e336f8067935b3b8e0e81db28/tests/test_conversion_base.py#L424), where exactly this is done. Can you provide more details like the code part that does the conversion, Sigma rule and processing pipeline?

**Comment by barvhaim** [comment]
@thomaspatzke I don't see this issue occur on other backends, but when I use mapping pipeline 

```
def stix_2_0() -> ProcessingPipeline:
    """This is a pipeline that maps fields to the STIX 2.0 format."""
    return ProcessingPipeline(
        name="stix 2.0",
        priority=100,
        items=[
            ProcessingItem(
                identifier="stix_2_0",
                transformation=FieldMappingTransformation({"f1": "f2"}),
            )
        ]
    )
```

and the rule is:

```
title: Test
status: test
logsource:
    category: test_category
    product: windows
detection:
    sel1:
        f1|re: '\$PSHome\[\s*\d{1,3}\s*\]\s*\+\s*\$PSHome\['
    condition: sel1
```

I get this error:
```
Error while conversion: Modifier SigmaRegularExpressionModifier incompatible to value type of 'SigmaRegularExpression(regexp='\\$PSHome\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$PSHome\\[')'
```

but when the rule has field name other than the field I have mapping for (for example `f3`), then it works fine

```
[f3 MATCHES '\$PSHome\[\s*\d{1,3}\s*\]\s*\+\s*\$PSHome\[']
```

So I wonder why it is happening

**Comment by barvhaim** [comment]
@thomaspatzke after exploring a bit I see this issue coming from `dataclasses.replace(detection_item, field=field) for field in mapping` inside the `SigmaDetection` creation on `transformations.py`, any ideas why we're getting this issue?

<img width="585" alt="image" src="https://user-images.githubusercontent.com/16198896/207644815-c116da1b-1935-4f2c-81fe-31e56db04ba5.png">

**Comment by barvhaim** [comment]
I found a way to reproduce, I will open a bug in a new issue, closing this one
