### ISSUE TITLE
TODO: Port Filename Convention Test

### ISSUE THREAD

**Issue by nasbench** [SigmaHQ/pySigma#89]
This issue serves as a reminder to port the newly introduced test to SIGMA in [PR #3812](https://github.com/SigmaHQ/sigma/pull/3812) that resolved [Issue #1381](https://github.com/SigmaHQ/sigma/issues/1381)

**Comment by thomaspatzke** [comment]
It's now part of the [rule check port project](https://github.com/orgs/SigmaHQ/projects/4) and tracked there.
